// Package store defines the persistence contract for the control plane.
// Two implementations exist: postgres (production) and memory (unit tests).
// Every org-scoped method MUST enforce org scoping internally — handlers pass
// the caller's org and the store guarantees no cross-org reads/writes
// (MULTI_TENANCY §2 "control plane data").
package store

import (
	"context"
	"errors"
	"time"

	"github.com/zenulbashar/DB/services/control-plane/internal/domain"
)

var (
	ErrNotFound        = errors.New("not found")
	ErrConflict        = errors.New("conflict")
	ErrLastOwner       = errors.New("would remove last owner")
	ErrAlreadyBoot     = errors.New("platform already bootstrapped")
	ErrKeyInvalid      = errors.New("api key invalid or revoked")
	ErrValidation      = errors.New("validation failed")
	ErrIdempotencyBusy = errors.New("idempotency key currently in flight")
	ErrDefaultBranch   = errors.New("cannot delete the default branch")
)

type BootstrapParams struct {
	Email   string
	Name    *string
	OrgName string
	// Key material is generated by the caller (auth package) so the store
	// never sees plaintext-generation responsibility.
	KeyName   string
	KeyHash   string
	KeyPrefix string
	Scopes    []domain.Scope
}

type BootstrapResult struct {
	Org    domain.Org
	User   domain.User
	APIKey domain.APIKey
}

// APIKeyAuth is what the auth middleware needs to build a principal.
type APIKeyAuth struct {
	Key domain.APIKey
}

type CreateAPIKeyParams struct {
	OrgID     string
	Name      string
	Hash      string
	Prefix    string
	Scopes    []domain.Scope
	ExpiresAt *time.Time
	CreatedBy *string
}

// SecretMaterial is prepared by the handler layer (which owns the keyring);
// stores only ever see ciphertext.
type SecretMaterial struct {
	Ciphertext []byte
	KeyVersion uint32
}

// ProjectSeed provisions the initial owner role + database records on the
// default branch, atomically with project creation (DATABASE_ARCHITECTURE §8).
type ProjectSeed struct {
	RoleName     string
	DatabaseName string
	Secret       SecretMaterial
}

type CreateProjectParams struct {
	OrgID     string
	Name      string
	Region    string
	PGVersion int
	Seed      *ProjectSeed
}

type CreateDBRoleParams struct {
	OrgID    string
	BranchID string
	Name     string
	Secret   SecretMaterial
}

type CreateImportParams struct {
	OrgID          string
	ProjectID      string
	TargetBranchID *string
	SourceKind     domain.ImportSourceKind
	Mode           domain.ImportMode
	SourceSecret   SecretMaterial // encrypted source connection string
}

type TransitionImportParams struct {
	To          domain.ImportState
	Report      map[string]any // set on preflight completion
	Checkpoints map[string]any // merged shallowly over existing keys
	Error       *string
}

// ClaimedImport is what a platform import worker needs to drive one stage. The
// source URL is returned as ciphertext; the worker decrypts it with the
// keyring (credentials never cross the tenant HTTP API).
type ClaimedImport struct {
	ImportID         string
	ProjectID        string
	OrgID            string
	TargetBranchID   *string
	SourceKind       domain.ImportSourceKind
	Mode             domain.ImportMode
	State            domain.ImportState
	Region           string
	SourceCiphertext []byte
	SourceKeyVersion int
}

type CreateBranchParams struct {
	OrgID     string
	ProjectID string
	Name      string
	ParentID  *string
	Role      domain.BranchRole
	Compute   domain.Compute // zero-valued fields take schema defaults
	Region    string         // for endpoint host derivation
}

type UpdateBranchParams struct {
	Name            *string
	MinCU           *float64
	MaxCU           *float64
	SuspendTimeoutS *int
	RetentionDays   *int
}

type Page struct {
	Limit  int
	Cursor string // exclusive; IDs are ULID-sortable, listing is newest-first
}

type IdempotentResponse struct {
	Status int
	Body   []byte
}

type Store interface {
	// --- privileged (pre-org-resolution) paths ---
	Bootstrapped(ctx context.Context) (bool, error)
	Bootstrap(ctx context.Context, p BootstrapParams) (*BootstrapResult, error)
	FindAPIKeyByHash(ctx context.Context, hash string) (*APIKeyAuth, error)
	TouchAPIKey(ctx context.Context, keyID string, at time.Time) error

	// --- org-scoped ---
	GetOrg(ctx context.Context, orgID string) (*domain.Org, error)
	UpdateOrgName(ctx context.Context, orgID, name string) (*domain.Org, error)

	ListMembers(ctx context.Context, orgID string) ([]domain.Member, error)
	AddMember(ctx context.Context, orgID, email string, name *string, role domain.OrgRole) (*domain.Member, error)
	UpdateMemberRole(ctx context.Context, orgID, userID string, role domain.OrgRole) (*domain.Member, error)
	RemoveMember(ctx context.Context, orgID, userID string) error

	CreateAPIKey(ctx context.Context, p CreateAPIKeyParams) (*domain.APIKey, error)
	ListAPIKeys(ctx context.Context, orgID string) ([]domain.APIKey, error)
	RevokeAPIKey(ctx context.Context, orgID, keyID string, at time.Time) error

	// CreateProject atomically provisions the project record, its default
	// branch "main" (role production), and that branch's rw_direct +
	// rw_pooled endpoint records in `provisioning` state.
	CreateProject(ctx context.Context, p CreateProjectParams) (*domain.Project, error)
	GetProject(ctx context.Context, orgID, projectID string) (*domain.Project, error)
	ListProjects(ctx context.Context, orgID string, pg Page) ([]domain.Project, string, error)
	UpdateProjectName(ctx context.Context, orgID, projectID, name string) (*domain.Project, error)
	SoftDeleteProject(ctx context.Context, orgID, projectID string, at time.Time) error

	// CreateBranch also creates the branch's rw_direct + rw_pooled endpoints.
	CreateBranch(ctx context.Context, p CreateBranchParams) (*domain.Branch, error)
	GetBranch(ctx context.Context, orgID, branchID string) (*domain.Branch, error) // endpoints populated
	ListBranches(ctx context.Context, orgID, projectID string, pg Page) ([]domain.Branch, string, error)
	UpdateBranch(ctx context.Context, orgID, branchID string, p UpdateBranchParams) (*domain.Branch, error)
	SoftDeleteBranch(ctx context.Context, orgID, branchID string, at time.Time) error // ErrDefaultBranch for the default
	// SuspendBranch flips a ready branch (and its endpoints) to suspending —
	// the reconciler then hibernates the compute and marks it suspended
	// (ADR-014). ResumeBranch flips a suspended branch to resuming (the
	// wake-on-connect trigger). Both are idempotent: a suspend on an
	// already-suspending/suspended branch, or a resume on an
	// already-resuming/ready branch, is a no-op success (so a wake coalesces).
	// Any other current state returns ErrConflict; a missing/deleting branch
	// returns ErrNotFound.
	SuspendBranch(ctx context.Context, orgID, branchID string) (*domain.Branch, error)
	ResumeBranch(ctx context.Context, orgID, branchID string) (*domain.Branch, error)
	// WakeBranchByID is the PRIVILEGED, cross-tenant resume the pg-gateway calls
	// for wake-on-connect (ADR-014): the gateway serves every tenant and has no
	// org-scoped credential, so it addresses a branch by ID. It resolves the
	// owning org and applies the same idempotent suspended→resuming flip as
	// ResumeBranch. ErrNotFound for a missing/deleting branch.
	WakeBranchByID(ctx context.Context, branchID string) (*domain.Branch, error)
	ListEndpoints(ctx context.Context, orgID, branchID string) ([]domain.Endpoint, error)
	// CreateEndpoint adds an endpoint (e.g. a read replica ro_pooled) to a
	// branch in provisioning state; the reconciler builds its backing resources
	// and marks it ready. ErrConflict if an endpoint of that kind already
	// exists; ErrNotFound for a missing/deleting branch.
	CreateEndpoint(ctx context.Context, orgID, branchID string, kind domain.EndpointKind) (*domain.Endpoint, error)

	CreateDBRole(ctx context.Context, p CreateDBRoleParams) (*domain.DBRole, error)
	ListDBRoles(ctx context.Context, orgID, branchID string) ([]domain.DBRole, error)
	DeleteDBRole(ctx context.Context, orgID, branchID, name string) error // ErrConflict if a database owner
	ResetDBRolePassword(ctx context.Context, orgID, branchID, name string, secret SecretMaterial) error
	// GetDBRoleSecret returns the role's password ciphertext for the audited
	// connection-URI reveal path.
	GetDBRoleSecret(ctx context.Context, orgID, branchID, name string) ([]byte, error)

	CreateDatabase(ctx context.Context, orgID, branchID, name, ownerRoleName string) (*domain.Database, error)
	ListDatabases(ctx context.Context, orgID, branchID string) ([]domain.Database, error)
	DeleteDatabase(ctx context.Context, orgID, branchID, name string) error

	// CreateImport stores the job with its source connection string as an
	// envelope-encrypted secret (never returned by any read path).
	CreateImport(ctx context.Context, p CreateImportParams) (*domain.Import, error)
	GetImport(ctx context.Context, orgID, importID string) (*domain.Import, error)
	ListImports(ctx context.Context, orgID, projectID string, pg Page) ([]domain.Import, string, error)
	// TransitionImport enforces domain.CanTransition; illegal steps return
	// ErrConflict. Checkpoints/report/error patches ride along atomically.
	TransitionImport(ctx context.Context, orgID, importID string, p TransitionImportParams) (*domain.Import, error)

	// ReportGatewayActivity records a gateway replica's per-branch active
	// connection counts for the suspend-on-idle decision (ADR-015). Privileged:
	// the caller is the pg-gateway via the internal API, not a tenant.
	ReportGatewayActivity(ctx context.Context, gatewayID string, counts map[string]int) error

	AppendAudit(ctx context.Context, e domain.AuditEntry) error
	ListAudit(ctx context.Context, orgID string, pg Page) ([]domain.AuditEntry, string, error)

	// --- idempotency (API_SPECIFICATION §1) ---
	GetIdempotent(ctx context.Context, orgID, route, key string) (*IdempotentResponse, error)
	PutIdempotent(ctx context.Context, orgID, route, key string, resp IdempotentResponse, expires time.Time) error

	Close()
}
