// Package store defines the persistence contract for the control plane.
// Two implementations exist: postgres (production) and memory (unit tests).
// Every org-scoped method MUST enforce org scoping internally — handlers pass
// the caller's org and the store guarantees no cross-org reads/writes
// (MULTI_TENANCY §2 "control plane data").
package store

import (
	"context"
	"errors"
	"time"

	"github.com/zenulbashar/DB/services/control-plane/internal/domain"
)

var (
	ErrNotFound        = errors.New("not found")
	ErrConflict        = errors.New("conflict")
	ErrLastOwner       = errors.New("would remove last owner")
	ErrAlreadyBoot     = errors.New("platform already bootstrapped")
	ErrKeyInvalid      = errors.New("api key invalid or revoked")
	ErrValidation      = errors.New("validation failed")
	ErrIdempotencyBusy = errors.New("idempotency key currently in flight")
)

type BootstrapParams struct {
	Email   string
	Name    *string
	OrgName string
	// Key material is generated by the caller (auth package) so the store
	// never sees plaintext-generation responsibility.
	KeyName   string
	KeyHash   string
	KeyPrefix string
	Scopes    []domain.Scope
}

type BootstrapResult struct {
	Org    domain.Org
	User   domain.User
	APIKey domain.APIKey
}

// APIKeyAuth is what the auth middleware needs to build a principal.
type APIKeyAuth struct {
	Key domain.APIKey
}

type CreateAPIKeyParams struct {
	OrgID     string
	Name      string
	Hash      string
	Prefix    string
	Scopes    []domain.Scope
	ExpiresAt *time.Time
	CreatedBy *string
}

type CreateProjectParams struct {
	OrgID     string
	Name      string
	Region    string
	PGVersion int
}

type Page struct {
	Limit  int
	Cursor string // exclusive; IDs are ULID-sortable, listing is newest-first
}

type IdempotentResponse struct {
	Status int
	Body   []byte
}

type Store interface {
	// --- privileged (pre-org-resolution) paths ---
	Bootstrapped(ctx context.Context) (bool, error)
	Bootstrap(ctx context.Context, p BootstrapParams) (*BootstrapResult, error)
	FindAPIKeyByHash(ctx context.Context, hash string) (*APIKeyAuth, error)
	TouchAPIKey(ctx context.Context, keyID string, at time.Time) error

	// --- org-scoped ---
	GetOrg(ctx context.Context, orgID string) (*domain.Org, error)
	UpdateOrgName(ctx context.Context, orgID, name string) (*domain.Org, error)

	ListMembers(ctx context.Context, orgID string) ([]domain.Member, error)
	AddMember(ctx context.Context, orgID, email string, name *string, role domain.OrgRole) (*domain.Member, error)
	UpdateMemberRole(ctx context.Context, orgID, userID string, role domain.OrgRole) (*domain.Member, error)
	RemoveMember(ctx context.Context, orgID, userID string) error

	CreateAPIKey(ctx context.Context, p CreateAPIKeyParams) (*domain.APIKey, error)
	ListAPIKeys(ctx context.Context, orgID string) ([]domain.APIKey, error)
	RevokeAPIKey(ctx context.Context, orgID, keyID string, at time.Time) error

	CreateProject(ctx context.Context, p CreateProjectParams) (*domain.Project, error)
	GetProject(ctx context.Context, orgID, projectID string) (*domain.Project, error)
	ListProjects(ctx context.Context, orgID string, pg Page) ([]domain.Project, string, error)
	UpdateProjectName(ctx context.Context, orgID, projectID, name string) (*domain.Project, error)
	SoftDeleteProject(ctx context.Context, orgID, projectID string, at time.Time) error

	AppendAudit(ctx context.Context, e domain.AuditEntry) error
	ListAudit(ctx context.Context, orgID string, pg Page) ([]domain.AuditEntry, string, error)

	// --- idempotency (API_SPECIFICATION §1) ---
	GetIdempotent(ctx context.Context, orgID, route, key string) (*IdempotentResponse, error)
	PutIdempotent(ctx context.Context, orgID, route, key string, resp IdempotentResponse, expires time.Time) error

	Close()
}
