/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-time platform bootstrap (ADR-013)
         * @description Creates the initial user, organization, and owner API key. Requires the
         *     `NDB_BOOTSTRAP_TOKEN` configured on the server and succeeds only while no
         *     organization exists. The returned API key is shown exactly once.
         */
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations visible to the caller's key */
        get: operations["listOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** Get an organization */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an organization */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/orgs/{org}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List organization members */
        get: operations["listMembers"];
        put?: never;
        /**
         * Add an organization member
         * @description Adds (or invites, once console auth exists in Phase 3) a member by email.
         */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an organization member */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/orgs/{org}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List API keys */
        get: operations["listApiKeys"];
        put?: never;
        /** Create an API key */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/api-keys/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List audit-log entries */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project
         * @description Phase 1: creates the project *record* (state `pending`); data-plane provisioning
         *     attaches in Phase 2 via the reconciler.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{prj}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["updateProject"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            request_id?: string;
        };
        /** @enum {string} */
        OrgRole: "owner" | "admin" | "member" | "viewer";
        /** @enum {string} */
        Scope: "orgs:read" | "projects:read" | "projects:write" | "projects:provision" | "branches:read" | "branches:write" | "endpoints:read" | "roles:read" | "roles:write" | "backups:read" | "backups:write" | "restores:write" | "imports:read" | "imports:write" | "metrics:read" | "audit:read" | "keys:manage" | "webhooks:manage" | "usage:read";
        Org: {
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            created_at: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Member: {
            org_id: string;
            user: components["schemas"]["User"];
            role: components["schemas"]["OrgRole"];
            /** Format: date-time */
            added_at: string;
        };
        ApiKey: {
            id: string;
            org_id: string;
            name: string;
            /** @description First 12 characters of the token, for identification. */
            prefix: string;
            scopes: components["schemas"]["Scope"][];
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ApiKeyWithSecret: components["schemas"]["ApiKey"] & {
            /** @description Full secret token. Returned exactly once; store it now. */
            token: string;
        };
        Project: {
            id: string;
            org_id: string;
            name: string;
            slug: string;
            region: string;
            pg_version: number;
            /**
             * @description Phase 1 records stay `pending`; the Phase 2 reconciler drives the rest.
             * @enum {string}
             */
            state: "pending" | "provisioning" | "ready" | "error" | "deleting";
            /** Format: date-time */
            created_at: string;
        };
        AuditEntry: {
            id: string;
            org_id: string;
            /** @enum {string} */
            actor_type: "api_key" | "user" | "system";
            actor_id: string;
            /** @description e.g. project.create, api_key.revoke */
            action: string;
            target_type: string;
            target_id: string;
            ip?: string | null;
            /** Format: date-time */
            at: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description Error (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Organization ID (`org_…`) */
        org: string;
        limit: number;
        cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        version?: string;
                    };
                };
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    bootstrap_token: string;
                    /** Format: email */
                    email: string;
                    name?: string;
                    org_name: string;
                };
            };
        };
        responses: {
            /** @description Platform bootstrapped */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        org: components["schemas"]["Org"];
                        user: components["schemas"]["User"];
                        api_key: components["schemas"]["ApiKeyWithSecret"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            /** @description Platform already bootstrapped */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listOrgs: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Org"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Updated organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Member"][];
                    };
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @description Display name used if the user record is created by this call */
                    name?: string;
                    role: components["schemas"]["OrgRole"];
                };
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Would remove the last owner */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["OrgRole"];
                };
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Would remove the last owner */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API keys (metadata only; secrets are never re-shown) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ApiKey"][];
                    };
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    scopes: components["schemas"]["Scope"][];
                    /** Format: date-time */
                    expires_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Created key — secret shown exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyWithSecret"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditEntry"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                org?: string;
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    org_id: string;
                    name: string;
                    /** @default syd1 */
                    region?: string;
                    /**
                     * @default 17
                     * @enum {integer}
                     */
                    pg_version?: 16 | 17;
                };
            };
        };
        responses: {
            /** @description Created project record */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (soft; lifecycle per MULTI_TENANCY §5) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
}
