/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-time platform bootstrap (ADR-013)
         * @description Creates the initial user, organization, and owner API key. Requires the
         *     `NDB_BOOTSTRAP_TOKEN` configured on the server and succeeds only while no
         *     organization exists. The returned API key is shown exactly once.
         */
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations visible to the caller's key */
        get: operations["listOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** Get an organization */
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an organization */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/orgs/{org}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List organization members */
        get: operations["listMembers"];
        put?: never;
        /**
         * Add an organization member
         * @description Adds (or invites, once console auth exists in Phase 3) a member by email.
         */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an organization member */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change a member's role */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/orgs/{org}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List API keys */
        get: operations["listApiKeys"];
        put?: never;
        /** Create an API key */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/api-keys/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org}/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        /** List audit-log entries */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project
         * @description Phase 1: creates the project *record* (state `pending`); data-plane provisioning
         *     attaches in Phase 2 via the reconciler.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{prj}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{prj}/connection-uri": {
        parameters: {
            query?: {
                branch?: string;
                endpoint?: "rw_pooled" | "rw_direct" | "ro_pooled";
                role?: string;
                database?: string;
                /** @description Requires `roles:write`; every reveal is audit-logged. */
                reveal?: boolean;
            };
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        /** Assemble a connection string (masked by default) */
        get: operations["getConnectionUri"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{prj}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        /** List branches of a project */
        get: operations["listBranches"];
        put?: never;
        /**
         * Create a branch
         * @description Creates a branch with its rw_direct + rw_pooled endpoints in
         *     `provisioning` state. A branch is a **data fork** of `from_branch`
         *     (defaults to the project's default branch): the reconciler bootstraps its
         *     cluster by recovery from the parent's WAL archive. `at` (RFC3339) forks
         *     from that point in time instead of the parent's latest state; it requires
         *     `from_branch` and must fall within the parent's backup retention window.
         */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        /** Get a branch with its endpoints */
        get: operations["getBranch"];
        put?: never;
        post?: never;
        /** Delete a branch */
        delete: operations["deleteBranch"];
        options?: never;
        head?: never;
        /** Update branch settings */
        patch: operations["updateBranch"];
        trace?: never;
    };
    "/branches/{br}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a branch's compute (scale-to-zero)
         * @description Flips a ready branch to `suspending`; the reconciler then hibernates the compute and marks it `suspended`. Idempotent — suspending an already-suspending/suspended branch is a no-op success. A branch that is provisioning/deleting/error returns 409.
         */
        post: operations["suspendBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume (wake) a suspended branch's compute
         * @description Flips a suspended branch to `resuming`; the reconciler un-hibernates the compute and marks it `ready`. This is also the wake-on-connect trigger the gateway calls (ADR-014); it is idempotent and coalesced, so a connection storm produces at most one wake.
         */
        post: operations["resumeBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vertically resize a branch's compute
         * @description Sets the branch's running compute size (`current_cu`), clamped to its `min_cu`/`max_cu` bounds, and flips it `ready → resizing`; the reconciler re-applies the cluster at the new size (zero-downtime, replica-first on HA) and flips it back to `ready`. This is also the action a metrics-driven autoscaler drives. 409 if the branch is not in a resizable state.
         */
        post: operations["resizeBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{prj}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        /** List imports for a project */
        get: operations["listImports"];
        put?: never;
        /**
         * Start a database import
         * @description The source connection URL is envelope-encrypted at rest and never
         *     returned by any read path. Runner workers drive the state machine via
         *     PATCH /imports/{imp}/state; cutover is a separate human gate.
         */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{imp}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        /** Get an import */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{imp}/cutover": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute cutover (only from cutover_ready) */
        post: operations["cutoverImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{imp}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort an import (any non-terminal state except cut_over) */
        post: operations["abortImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{imp}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance the import state machine (runner-facing) */
        patch: operations["updateImportState"];
        trace?: never;
    };
    "/branches/{br}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        /** List database roles */
        get: operations["listDbRoles"];
        put?: never;
        /** Create a database role */
        post: operations["createDbRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                role: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a database role */
        delete: operations["deleteDbRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/roles/{role}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                role: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a role's password */
        post: operations["resetDbRolePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/databases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        /** List databases */
        get: operations["listDatabases"];
        put?: never;
        /** Create a database */
        post: operations["createDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/databases/{db}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                db: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a database */
        delete: operations["deleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{br}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        /** List a branch's endpoints */
        get: operations["listEndpoints"];
        put?: never;
        /**
         * Add an endpoint to a branch (e.g. a read replica)
         * @description Adds an endpoint of the given kind. `ro_pooled` provisions a read replica: the reconciler scales the branch's cluster to a primary + hot-standby and fronts the replicas with a read pooler. The new endpoint starts `provisioning` and becomes `ready` once its backing resources are up. 409 if an endpoint of that kind already exists (branches ship with `rw_direct` + `rw_pooled`).
         */
        post: operations["createEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            request_id?: string;
        };
        /** @enum {string} */
        OrgRole: "owner" | "admin" | "member" | "viewer";
        /** @enum {string} */
        Scope: "orgs:read" | "orgs:write" | "members:manage" | "projects:read" | "projects:write" | "projects:provision" | "branches:read" | "branches:write" | "endpoints:read" | "roles:read" | "roles:write" | "backups:read" | "backups:write" | "restores:write" | "imports:read" | "imports:write" | "metrics:read" | "audit:read" | "keys:manage" | "webhooks:manage" | "usage:read";
        Org: {
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            created_at: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Member: {
            org_id: string;
            user: components["schemas"]["User"];
            role: components["schemas"]["OrgRole"];
            /** Format: date-time */
            added_at: string;
        };
        ApiKey: {
            id: string;
            org_id: string;
            name: string;
            /** @description First 12 characters of the token, for identification. */
            prefix: string;
            scopes: components["schemas"]["Scope"][];
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ApiKeyWithSecret: components["schemas"]["ApiKey"] & {
            /** @description Full secret token. Returned exactly once; store it now. */
            token: string;
        };
        Project: {
            id: string;
            org_id: string;
            name: string;
            slug: string;
            region: string;
            pg_version: number;
            /**
             * @description Phase 1 records stay `pending`; the Phase 2 reconciler drives the rest.
             * @enum {string}
             */
            state: "pending" | "provisioning" | "ready" | "error" | "deleting";
            default_branch_id: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        BranchRole: "production" | "preview" | "development";
        /**
         * @description Lifecycle/compute state shared by branches and endpoints. `suspending` and `resuming` are transient scale-to-zero states the reconciler converges (ADR-014); `resizing` is the transient vertical-resize state while the cluster is re-applied at a new compute size.
         * @enum {string}
         */
        ResourceState: "provisioning" | "ready" | "suspending" | "suspended" | "resuming" | "resizing" | "error" | "deleting";
        Compute: {
            min_cu: number;
            max_cu: number;
            /** @description Actual running size, autoscaled between min_cu and max_cu (0 before the first resize). */
            current_cu?: number;
            suspend_timeout_s: number;
        };
        Branch: {
            id: string;
            project_id: string;
            parent: string | null;
            name: string;
            role: components["schemas"]["BranchRole"];
            state: components["schemas"]["ResourceState"];
            compute: components["schemas"]["Compute"];
            retention_days: number;
            /**
             * Format: date-time
             * @description Point-in-time this branch was forked from its parent; null if forked from the latest state or a root branch.
             */
            bootstrap_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Present on single-branch reads and creation responses. */
            endpoints?: components["schemas"]["Endpoint"][];
        };
        Endpoint: {
            id: string;
            branch_id: string;
            /** @enum {string} */
            kind: "rw_direct" | "rw_pooled" | "ro_pooled";
            host: string;
            state: components["schemas"]["ResourceState"];
            /** Format: date-time */
            created_at: string;
        };
        DBRole: {
            id: string;
            branch_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        DBRoleWithPassword: components["schemas"]["DBRole"] & {
            /** @description Returned exactly once; store it now. */
            password: string;
        };
        Database: {
            id: string;
            branch_id: string;
            name: string;
            owner_role_id: string;
            /** Format: date-time */
            created_at: string;
        };
        ProjectCreated: {
            project: components["schemas"]["Project"];
            owner_role: {
                name: string;
                /** @description Returned exactly once. */
                password: string;
            };
            database: {
                name: string;
            };
        };
        /** @enum {string} */
        ImportState: "pending" | "preflight" | "schema_copy" | "initial_copy" | "live_sync" | "cutover_ready" | "cut_over" | "verified" | "failed" | "aborted";
        Import: {
            id: string;
            project_id: string;
            target_branch_id: string | null;
            /** @enum {string} */
            source_kind: "neon" | "supabase" | "rds" | "azure" | "generic";
            /** @enum {string} */
            mode: "dump_restore" | "logical_replication";
            state: components["schemas"]["ImportState"];
            /** @description Preflight report (set once preflight completes). */
            report?: {
                [key: string]: unknown;
            };
            /** @description Progress markers merged across transitions. */
            checkpoints?: {
                [key: string]: unknown;
            };
            error: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuditEntry: {
            id: string;
            org_id: string;
            /** @enum {string} */
            actor_type: "api_key" | "user" | "system";
            actor_id: string;
            /** @description e.g. project.create, api_key.revoke */
            action: string;
            target_type: string;
            target_id: string;
            ip?: string | null;
            /** Format: date-time */
            at: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description Error (RFC 9457) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Organization ID (`org_…`) */
        org: string;
        limit: number;
        cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        version?: string;
                    };
                };
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    bootstrap_token: string;
                    /** Format: email */
                    email: string;
                    name?: string;
                    org_name: string;
                };
            };
        };
        responses: {
            /** @description Platform bootstrapped */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        org: components["schemas"]["Org"];
                        user: components["schemas"]["User"];
                        api_key: components["schemas"]["ApiKeyWithSecret"];
                    };
                };
            };
            403: components["responses"]["Problem"];
            /** @description Platform already bootstrapped */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listOrgs: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Org"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Updated organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Org"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Member"][];
                    };
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @description Display name used if the user record is created by this call */
                    name?: string;
                    role: components["schemas"]["OrgRole"];
                };
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Would remove the last owner */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                user: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["OrgRole"];
                };
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Would remove the last owner */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API keys (metadata only; secrets are never re-shown) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ApiKey"][];
                    };
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    scopes: components["schemas"]["Scope"][];
                    /** Format: date-time */
                    expires_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Created key — secret shown exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyWithSecret"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path: {
                /** @description Organization ID (`org_…`) */
                org: components["parameters"]["org"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditEntry"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                org?: string;
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    org_id: string;
                    name: string;
                    /**
                     * @default syd1
                     * @enum {string}
                     */
                    region?: "syd1";
                    /**
                     * @default 17
                     * @enum {integer}
                     */
                    pg_version?: 16 | 17;
                };
            };
        };
        responses: {
            /**
             * @description Created project with its seeded owner role and database on the
             *     default branch. The role password is returned exactly once.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreated"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (soft; lifecycle per MULTI_TENANCY §5) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getConnectionUri: {
        parameters: {
            query?: {
                branch?: string;
                endpoint?: "rw_pooled" | "rw_direct" | "ro_pooled";
                role?: string;
                database?: string;
                /** @description Requires `roles:write`; every reveal is audit-logged. */
                reveal?: boolean;
            };
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection URI (never cached) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uri: string;
                        endpoint: string;
                        branch_id: string;
                        role: string;
                        database: string;
                        revealed: boolean;
                    };
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listBranches: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branches (endpoints omitted; fetch a branch for them) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Branch"][];
                        next_cursor?: string | null;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    from_branch?: string | null;
                    /**
                     * Format: date-time
                     * @description Point-in-time fork target (RFC3339); requires from_branch.
                     */
                    at?: string;
                    role?: components["schemas"]["BranchRole"];
                    compute_min_cu?: number;
                    compute_max_cu?: number;
                    suspend_timeout_s?: number;
                };
            };
        };
        responses: {
            /** @description Created branch (with endpoints) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            /** @description Default branch is delete-protected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    compute_min_cu?: number;
                    compute_max_cu?: number;
                    suspend_timeout_s?: number;
                    retention_days?: number;
                };
            };
        };
        responses: {
            /** @description Updated branch */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    suspendBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch (now suspending or already suspended) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    resumeBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Branch (now resuming or already ready) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    resizeBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cu: number;
                };
            };
        };
        responses: {
            /** @description Branch (now resizing or already at size) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listImports: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                cursor?: components["parameters"]["cursor"];
            };
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Import"][];
                        next_cursor?: string | null;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prj: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    source_kind: "neon" | "supabase" | "rds" | "azure" | "generic";
                    /** @enum {string} */
                    mode: "dump_restore" | "logical_replication";
                    /** @description postgres:// URL of the source (write-only). */
                    source_url: string;
                    target_branch?: string | null;
                };
            };
        };
        responses: {
            /** @description Created import (state pending) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    cutoverImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import now cut_over */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    abortImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import aborted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    updateImportState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imp: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: components["schemas"]["ImportState"];
                    report?: {
                        [key: string]: unknown;
                    };
                    checkpoints?: {
                        [key: string]: unknown;
                    };
                    error?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated import */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Import"];
                };
            };
            /** @description Illegal transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDbRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles (never includes secret material) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DBRole"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createDbRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created role — password shown exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DBRoleWithPassword"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteDbRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            /** @description Role owns a database */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resetDbRolePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New password — shown exactly once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        password: string;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Databases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Database"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    owner_role: string;
                };
            };
        };
        responses: {
            /** @description Created database */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Database"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    listEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Endpoint"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    createEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                br: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "rw_direct" | "rw_pooled" | "ro_pooled";
                };
            };
        };
        responses: {
            /** @description Created endpoint */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Endpoint"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
}
